Repository ankr/vector.js, pull requests merged in 2023-05, with the labels that each got.

#11 Add release flow for npm registry
  .github/workflows/ensure-labels.yml
  .github/workflows/release.yml
Labels: skip-release

#12 Change package name
  README.md
  package.json
Labels: major

#13 Remove legacy publish workflow
  .github/pull_request_template.md
  .github/workflows/publish.yml
Labels: skip-release

#14 Cleanup
  .github/pull_request_template.md
  LICENSE
  README.md
  package.json
  src/Vector.js
  test/Vector.js
Labels: patch

#15 Add angle method
  index.js
  src/Vector.js
  test/Vector.js
Labels: patch

#16 Test dividing by zero is throwing error
  test/Vector.js
Labels: patch
